version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: superuser
      MYSQL_USER: superuser
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./data/database:/var/lib/mysql

  wp:
    image: wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_PASSWORD: superuser
      WORDPRESS_DB_USER: superuser
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    ports:
      - 80:80
    volumes:
      - ./data/uploads:/var/www/html/wp-content/uploads
      - ./data/themes:/var/www/html/wp-content/themes
      - ./plugins/easy-hidden-plugins:/var/www/html/wp-content/plugins/easy-hidden-plugins
